"""bot accounts and link codes

Revision ID: eb5052fa0d5c
Revises: 478f787d33bd
Create Date: 2026-10-01 23:24:27.586102

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb5052fa0d5c"
down_revision = "478f787d33bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "external_id", "user_id"),
    )
    with op.batch_alter_table("bot_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_accounts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "bot_link_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    with op.batch_alter_table("bot_link_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_link_codes_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_link_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_link_codes_user_id"))

    op.drop_table("bot_link_codes")
    with op.batch_alter_table("bot_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_accounts_user_id"))

    op.drop_table("bot_accounts")
    # ### end Alembic commands ###
